// 간단한 목업 데이터: 실제 연동 전 UI 구성용

export const chatRooms = [
  {
    id: '1',
    title: '뮤지컬 위키드 실시간 소감방',
    performanceName: 'Wicked',
    image: '/poster/wicked.gif',
    active: true,
    participants: 238,
    visitors: 124,
    lastMessage: '1막 넘버 미쳤다… 엘파바 라이브 소름',
    lastTime: '5분 전',
    creatorNickname: 'emerald-owl',
    popularity: 99,
  },
  {
    id: '2',
    title: '렌트 - 오늘 내한 첫공 후기',
    performanceName: 'RENT',
    image: '/poster/rent.gif',
    active: true,
    participants: 180,
    visitors: 96,
    lastMessage: '시즌 합창에서 눈물났음 ㅠㅠ',
    lastTime: '10분 전',
    creatorNickname: 'east-village',
    popularity: 92,
  },
  {
    id: '3',
    title: '물랑루즈 커튼콜 얘기만',
    performanceName: 'Moulin Rouge!',
    image: '/poster/moulin-rouge.gif',
    active: true,
    participants: 151,
    visitors: 78,
    lastMessage: '커튼콜 안무 합이 너무 좋았어요',
    lastTime: '22분 전',
    creatorNickname: 'satine-star',
    popularity: 88,
  },
  {
    id: '4',
    title: '한복입은 남자 - 캐스팅 정보 나눔',
    performanceName: '한복입은 남자',
    image: '/poster/hanbok-man.jpg',
    active: false,
    participants: 63,
    visitors: 21,
    lastMessage: '다음주 캐스팅표 공유드립니다',
    lastTime: '1시간 전',
    creatorNickname: 'sage-blue',
    popularity: 61,
  },
  {
    id: '5',
    title: '킹키부츠 떼창 모임',
    performanceName: 'Kinky Boots',
    image: '/poster/kinky-boots.gif',
    active: true,
    participants: 97,
    visitors: 40,
    lastMessage: '이따 9시에 모여요!',
    lastTime: '45분 전',
    creatorNickname: 'lola-heel',
    popularity: 75,
  },
  {
    id: '6',
    title: '데스노트 수록곡 최애 토론',
    performanceName: 'Death Note',
    image: '/poster/death-note.gif',
    active: false,
    participants: 54,
    visitors: 19,
    lastMessage: 'The Game Begins 인정?',
    lastTime: '2시간 전',
    creatorNickname: 'apple-ryuk',
    popularity: 58,
  },
];

export const getRoomById = (id) => chatRooms.find((r) => r.id === id);


