// 간단한 목업 데이터: 실제 연동 전 UI 구성용
import wickedPoster from '../../assets/poster/wicked.gif';
import moulinRougePoster from '../../assets/poster/moulin-rouge.gif';
import kinkyBootsPoster from '../../assets/poster/kinky-boots.gif';
import hanbokManPoster from '../../assets/poster/hanbok-man.jpg';
import deathNotePoster from '../../assets/poster/death-note.gif';
import rentPoster from '../../assets/poster/rent.gif';

export const chatRooms = [
  {
    id: '1',
    title: '뮤지컬 위키드 실시간 소감방',
    performanceName: 'Wicked',
    performanceId: 1, // 위키드 공연 ID
    image: wickedPoster,
    active: true,
    participants: 238,
    visitors: 124,
    lastMessage: '1막 넘버 미쳤다… 엘파바 라이브 소름',
    lastTime: '5분 전',
    creatorNickname: 'emerald-owl',
    popularity: 99,
    isMainRoom: true, // 주 채팅방 표시
  },
  {
    id: '2',
    title: '렌트 - 오늘 내한 첫공 후기',
    performanceName: 'RENT',
    performanceId: 6, // 렌트 공연 ID
    image: rentPoster,
    active: true,
    participants: 180,
    visitors: 96,
    lastMessage: '시즌 합창에서 눈물났음 ㅠㅠ',
    lastTime: '10분 전',
    creatorNickname: 'east-village',
    popularity: 92,
    isMainRoom: true,
  },
  {
    id: '3',
    title: '물랑루즈 커튼콜 얘기만',
    performanceName: 'Moulin Rouge!',
    performanceId: 2, // 물랑루즈 공연 ID
    image: moulinRougePoster,
    active: true,
    participants: 151,
    visitors: 78,
    lastMessage: '커튼콜 안무 합이 너무 좋았어요',
    lastTime: '22분 전',
    creatorNickname: 'satine-star',
    popularity: 88,
    isMainRoom: true,
  },
  {
    id: '4',
    title: '한복입은 남자 - 캐스팅 정보 나눔',
    performanceName: '한복입은 남자',
    performanceId: 4, // 한복입은 남자 공연 ID
    image: hanbokManPoster,
    active: false,
    participants: 63,
    visitors: 21,
    lastMessage: '다음주 캐스팅표 공유드립니다',
    lastTime: '1시간 전',
    creatorNickname: 'sage-blue',
    popularity: 61,
    isMainRoom: true,
  },
  {
    id: '5',
    title: '킹키부츠 떼창 모임',
    performanceName: 'Kinky Boots',
    performanceId: 3, // 킹키부츠 공연 ID
    image: kinkyBootsPoster,
    active: true,
    participants: 97,
    visitors: 40,
    lastMessage: '이따 9시에 모여요!',
    lastTime: '45분 전',
    creatorNickname: 'lola-heel',
    popularity: 75,
    isMainRoom: true,
  },
  {
    id: '6',
    title: '데스노트 수록곡 최애 토론',
    performanceName: 'Death Note',
    performanceId: 5, // 데스노트 공연 ID
    image: deathNotePoster,
    active: false,
    participants: 54,
    visitors: 19,
    lastMessage: 'The Game Begins 인정?',
    lastTime: '2시간 전',
    creatorNickname: 'apple-ryuk',
    popularity: 58,
    isMainRoom: true,
  },
  // 새로 추가된 공연들의 주 채팅방
  {
    id: '7',
    title: '햄릿 실시간 소감방',
    performanceName: 'HAMLET',
    performanceId: 7,
    image: wickedPoster,
    active: true,
    participants: 89,
    visitors: 45,
    lastMessage: '오늘 공연 정말 감동적이었어요',
    lastTime: '15분 전',
    creatorNickname: 'danish-prince',
    popularity: 72,
    isMainRoom: true,
  },
  {
    id: '8',
    title: '시카고 재즈 토론방',
    performanceName: 'CHICAGO',
    performanceId: 8,
    image: moulinRougePoster,
    active: true,
    participants: 134,
    visitors: 67,
    lastMessage: 'All That Jazz 넘버 정말 최고!',
    lastTime: '8분 전',
    creatorNickname: 'chicago-jazz',
    popularity: 81,
    isMainRoom: true,
  },
  {
    id: '9',
    title: '오페라의 유령 주 채팅방',
    performanceName: 'THE PHANTOM OF THE OPERA',
    performanceId: 9,
    image: kinkyBootsPoster,
    active: true,
    participants: 201,
    visitors: 102,
    lastMessage: 'Music of the Night 라이브 소름',
    lastTime: '3분 전',
    creatorNickname: 'phantom-opera',
    popularity: 95,
    isMainRoom: true,
  },
  {
    id: '10',
    title: '리어왕 공연 후기',
    performanceName: 'KING LEAR',
    performanceId: 10,
    image: hanbokManPoster,
    active: false,
    participants: 67,
    visitors: 28,
    lastMessage: '권력의 비극이 정말 인상적이었어요',
    lastTime: '1시간 전',
    creatorNickname: 'king-tragedy',
    popularity: 64,
    isMainRoom: true,
  },
  {
    id: '11',
    title: '레미제라블 실시간 채팅방',
    performanceName: 'LES MISÉRABLES',
    performanceId: 11,
    image: rentPoster,
    active: true,
    participants: 245,
    visitors: 128,
    lastMessage: 'I Dreamed a Dream에서 눈물',
    lastTime: '5분 전',
    creatorNickname: 'miserables-fan',
    popularity: 97,
    isMainRoom: true,
  },
  {
    id: '12',
    title: '맘마미아 추억 공유',
    performanceName: 'MAMMA MIA!',
    performanceId: 12,
    image: deathNotePoster,
    active: false,
    participants: 156,
    visitors: 78,
    lastMessage: 'ABBA 곡들이 정말 좋았어요',
    lastTime: '2시간 전',
    creatorNickname: 'abba-lover',
    popularity: 74,
    isMainRoom: true,
  },
  {
    id: '13',
    title: '햄릿 2024 후기 모음',
    performanceName: 'HAMLET (2024)',
    performanceId: 13,
    image: wickedPoster,
    active: false,
    participants: 112,
    visitors: 56,
    lastMessage: '셰익스피어의 명작이네요',
    lastTime: '3시간 전',
    creatorNickname: 'shakespeare-fan',
    popularity: 68,
    isMainRoom: true,
  },
  {
    id: '14',
    title: '라이온킹 가족 관람 후기',
    performanceName: 'THE LION KING',
    performanceId: 14,
    image: moulinRougePoster,
    active: false,
    participants: 198,
    visitors: 99,
    lastMessage: '아이들이 정말 좋아했어요',
    lastTime: '1시간 전',
    creatorNickname: 'lion-king-family',
    popularity: 86,
    isMainRoom: true,
  },
  {
    id: '15',
    title: '세일즈맨의 죽음 토론',
    performanceName: 'DEATH OF A SALESMAN',
    performanceId: 15,
    image: kinkyBootsPoster,
    active: false,
    participants: 78,
    visitors: 39,
    lastMessage: '현실적인 비극이 인상적이었어요',
    lastTime: '2시간 전',
    creatorNickname: 'miller-reader',
    popularity: 61,
    isMainRoom: true,
  },
  {
    id: '16',
    title: '캣츠 Jellicle Cats 모임',
    performanceName: 'CATS',
    performanceId: 16,
    image: hanbokManPoster,
    active: false,
    participants: 167,
    visitors: 84,
    lastMessage: 'Memory 넘버가 정말 아름다웠어요',
    lastTime: '1시간 전',
    creatorNickname: 'jellicle-cat',
    popularity: 79,
    isMainRoom: true,
  },
  {
    id: '17',
    title: '미스 사이공 기대평',
    performanceName: 'MISS SAIGON',
    performanceId: 17,
    image: rentPoster,
    active: false,
    participants: 45,
    visitors: 23,
    lastMessage: '공연 기대되네요!',
    lastTime: '30분 전',
    creatorNickname: 'saigon-wait',
    popularity: 52,
    isMainRoom: true,
  },
  {
    id: '18',
    title: '햄릿 2025 Summer 예매 완료',
    performanceName: 'HAMLET (2025 Summer)',
    performanceId: 18,
    image: deathNotePoster,
    active: false,
    participants: 38,
    visitors: 19,
    lastMessage: '여름 공연 기대됩니다',
    lastTime: '1시간 전',
    creatorNickname: 'summer-hamlet',
    popularity: 48,
    isMainRoom: true,
  },
  {
    id: '19',
    title: '에비타 예매 정보 공유',
    performanceName: 'EVITA',
    performanceId: 19,
    image: wickedPoster,
    active: false,
    participants: 52,
    visitors: 26,
    lastMessage: 'Don\'t Cry for Me Argentina 기대',
    lastTime: '45분 전',
    creatorNickname: 'evita-fan',
    popularity: 55,
    isMainRoom: true,
  },
  {
    id: '20',
    title: '오셀로 질투와 사랑 토론',
    performanceName: 'OTHELLO',
    performanceId: 20,
    image: moulinRougePoster,
    active: false,
    participants: 41,
    visitors: 21,
    lastMessage: '셰익스피어의 또 다른 명작',
    lastTime: '1시간 전',
    creatorNickname: 'othello-reader',
    popularity: 49,
    isMainRoom: true,
  },
  {
    id: '21',
    title: '드림걸스 R&B 뮤지컬 팬',
    performanceName: 'DREAMGIRLS',
    performanceId: 21,
    image: kinkyBootsPoster,
    active: false,
    participants: 47,
    visitors: 24,
    lastMessage: 'And I Am Telling You 기대돼요',
    lastTime: '1시간 전',
    creatorNickname: 'dreamgirls-fan',
    popularity: 53,
    isMainRoom: true,
  },
  // 콘서트 주 채팅방
  {
    id: '22',
    title: 'NCT WISH 콘서트 실시간 소감',
    performanceName: 'NCT WISH CONCERT',
    performanceId: 22,
    image: rentPoster,
    active: false,
    participants: 312,
    visitors: 156,
    lastMessage: 'NCT WISH 무대 정말 최고였어요!',
    lastTime: '2시간 전',
    creatorNickname: 'nct-wish-fan',
    popularity: 88,
    isMainRoom: true,
  },
  {
    id: '23',
    title: 'SKY FESTIVAL 예매 정보 공유',
    performanceName: 'SKY FESTIVAL 2025',
    performanceId: 23,
    image: moulinRougePoster,
    active: true,
    participants: 189,
    visitors: 95,
    lastMessage: '이번주 페스티벌 정말 기대돼요!',
    lastTime: '10분 전',
    creatorNickname: 'sky-festival',
    popularity: 92,
    isMainRoom: true,
  },
  {
    id: '24',
    title: '아이유 콘서트 기대평',
    performanceName: 'IU CONCERT - The Golden Hour',
    performanceId: 24,
    image: kinkyBootsPoster,
    active: false,
    participants: 267,
    visitors: 134,
    lastMessage: '아이유 라이브 정말 기대돼요',
    lastTime: '30분 전',
    creatorNickname: 'iu-fan',
    popularity: 85,
    isMainRoom: true,
  },
  {
    id: '25',
    title: 'BTS 콘서트 후기 모음',
    performanceName: 'BTS WORLD TOUR',
    performanceId: 25,
    image: wickedPoster,
    active: false,
    participants: 445,
    visitors: 223,
    lastMessage: 'BTS 콘서트 정말 최고였어요',
    lastTime: '1시간 전',
    creatorNickname: 'bts-army',
    popularity: 98,
    isMainRoom: true,
  },
  {
    id: '26',
    title: '뉴진스 콘서트 예매 완료',
    performanceName: 'NewJeans LIVE',
    performanceId: 26,
    image: deathNotePoster,
    active: false,
    participants: 178,
    visitors: 89,
    lastMessage: '뉴진스 라이브 정말 기대돼요',
    lastTime: '45분 전',
    creatorNickname: 'newjeans-bunny',
    popularity: 82,
    isMainRoom: true,
  },
  {
    id: '27',
    title: '세븐틴 콘서트 후기',
    performanceName: 'SEVENTEEN TOUR',
    performanceId: 27,
    image: hanbokManPoster,
    active: false,
    participants: 234,
    visitors: 117,
    lastMessage: '세븐틴 퍼포먼스 정말 최고였어요',
    lastTime: '1시간 전',
    creatorNickname: 'carat-fan',
    popularity: 87,
    isMainRoom: true,
  },
  {
    id: '28',
    title: '르세라핌 콘서트 기대평',
    performanceName: 'LE SSERAFIM LIVE',
    performanceId: 28,
    image: rentPoster,
    active: false,
    participants: 156,
    visitors: 78,
    lastMessage: '르세라핌 무대 정말 기대돼요',
    lastTime: '1시간 전',
    creatorNickname: 'fearnot-fan',
    popularity: 79,
    isMainRoom: true,
  },
];

// 공연 ID로 주 채팅방 찾기
export const getMainRoomByPerformanceId = (performanceId) => {
  return chatRooms.find((r) => r.performanceId === performanceId && r.isMainRoom);
};

export const getRoomById = (id) => chatRooms.find((r) => r.id === id);


